### ISSUE TITLE
New version for Odoo v.16

### ISSUE THREAD

**Issue by strategist922** [ECPay/Odoo_Payment#1]
Dear Support,

     When will ECPay release new version that support Odoo V16.x ?

**Comment by evica1492** [comment]
Hope ECPay supports the new version of Odoo V16.x  !

**Comment by gjlmotea** [comment]
same here!
未來會支援odoo新版本嗎？

**Comment by AllennChang** [comment]
您好, 目前正在研發Odoo 16的版本, 預計年底前會釋出給廠商使用,
